### ISSUE TITLE
printf does not work correctly under Minoca/Sh

### ISSUE THREAD

**Issue by melezhik** [melezhik/sparrowdo#17]
Probably not a Sparrowdo issue, have it here for thorough investigation. 

The same code works differently unsed Bash/Sh in Minoca OS:

When run in Bash shell

```
bash-4.3# OS=Minoca; OS=$(printf -- "$OS" | awk '{ print tolower($1) }');
bash-4.3# echo $?
0
bash-4.3# echo $OS
minoca

```

When run in Sh shell
```
~# OS=Minoca; OS=$(printf -- "$OS" | awk '{ print tolower($1) }');
~# echo $?
0
~# echo $OS
--
```

@Tyil any ideas why?

**Comment by Tyil** [comment]
It seems the `--` is interpreted as the format string, and `"$OS"` as the argument. I have some different solutions that might be applicable. I'll make a PR to test one soon. Is it possible to have a Docker target for Minoca so I can see the test results in Travis?

**Comment by melezhik** [comment]
Hi Patrick. Unfortunately minoca is not available by docker, but they provide daily images runnable under qemu, which you can tests against, following the links that help you start with : 

 - https://github.com/minoca/os/issues/95
- https://sparrowdo.wordpress.com/2017/09/20/minoca-os-automation-with-sparrowdo/
