### ISSUE TITLE
Can sparrowfile include another sparrowfile?

### ISSUE THREAD

**Issue by Spigell** [melezhik/sparrowdo#2]
Здравствуйте. Нигде не нашел простого способа использовать один sparrowfile в другом. Что-то аналогичное `run_module`, но для sparrowfile. Есть ли такая возможность?
Спасибо.

**Comment by melezhik** [comment]
Приветсвтую!

Внутри основного sparrowfile:

```
EVALFILE "/path/to/file";
```

**Comment by Spigell** [comment]
Спасибо!
