### ISSUE TITLE
обновление отчетов sparrow/sparrowdo

### ISSUE THREAD

**Issue by melezhik** [melezhik/sparrowdo#5]
Приветствую! Я сделал небольшие изменения в отчетах sparrpo/sparrowdo , рекомендую обновить sparrowdo и sparrow : 

```
$ zef update
$ zef install Sparrowdo # должна быть версия 0.0.9

$ sparrowdo --module_run=Sparrow::Update 
# или

cpanm https://github.com/melezhik/outthentic.git
cpanm https://github.com/melezhik/sparrow.git
```

Если будут какие-то баги, проблемы после обновления - пишите пож-та сюда.

Спасибо

PS ссылка на ваш ID - @Spigell

**Comment by Spigell** [comment]
Здравствуйте. Обновил. Проблем не возникло.

**Comment by melezhik** [comment]
Спасибо.
