### ISSUE TITLE
add --bootstrap for Archlinux

### ISSUE THREAD

**Issue by Spigell** [melezhik/sparrowdo#6]
Здравствуйте. Можете добавить поддержку archlinux для ключа --bootstrap?

**Comment by melezhik** [comment]
Думаю, что можно. А вы могли бы отписать сюда как вы на archlinux ставите sparrow руками, мне бы это помогло в написании команд бутстрапа для данной os.

**Comment by Spigell** [comment]
Здравствуйте. Да как обычно, в принципе.
root@archiso ~ # pacman -Sy cpanminus gcc make
root@archiso ~ # cpanm -n Sparrow

В установленном дистрибутиве есть уже gcc и make.

**Comment by Spigell** [comment]
Здравствуйте. Сейчас столкнулся с тем, что необходимо ставить inc::Module::Install руками. Хотя раньше такого не встречал. 
И да, я ошибся, gcc и make нет в только что установленной ОС.

**Comment by melezhik** [comment]
Приветствую! Какая версия Perl у вас на машине, где вы ставите sparrow?

**Comment by melezhik** [comment]
> И да, я ошибся, gcc и make нет в только что установленной ОС.

Да, такое бывает. В бутстрапе, который надёжно работает только для centos эти пакеты ставятся yum. В ближайшее время я планирую добавить поддержку других операционных систем в бутстрап, так что думаю, что проблема решится.

**Comment by Spigell** [comment]
```
[root@myArchlinux ~]# pacman -Qi perl
Name            : perl
Version         : 5.26.0-1
Description     : A highly capable, feature-rich programming language
Architecture    : x86_64
URL             : http://www.perl.org
Licenses        : GPL  PerlArtistic
```
Вот выдержка из лога:
```
Written by John Gilmore and Jay Fenlason.
Searching Sparrow () on cpanmetadb ...
--> Working on Sparrow
Fetching http://www.cpan.org/authors/id/M/ME/MELEZHIK/Sparrow-0.2.39.tar.gz
-> OK
Unpacking Sparrow-0.2.39.tar.gz
Entering Sparrow-0.2.39
Checking configure dependencies from META.yml
Checking if you have ExtUtils::MakeMaker 6.58 ... Yes (7.24)
Configuring Sparrow-0.2.39
Running Makefile.PL
Can't locate inc/Module/Install.pm in @INC (you may need to install the inc::Module::Install module) (@INC contains: /usr/lib/perl5/site_perl /usr/share/perl5/site_perl /usr/lib/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib/perl5/core_perl /usr/share/perl5/core_perl) at Makefile.PL line 1.
BEGIN failed--compilation aborted at Makefile.PL line 1.
-> N/A
-> FAIL Configure failed for Sparrow-0.2.39. See /root/.cpanm/work/1498760268.1741/build.log for details.
```

**Comment by melezhik** [comment]
У вас достаточно свежий Perl, как раз начиная с версии 5.26. была убрана текущая директория из путей в которых ищутся библиотеки , inc/Module/Install как раз одна из них, она поставляешься внутри дистрибутива ... надо будет подумать как это решить, пока временно сделаю решение на уровне Sparrowdo bootstrap, если вы конечно sparrow ставите ...

**Comment by melezhik** [comment]
Да, и ссылка по теме ,  если интересно - http://blfs-dev.linuxfromscratch.narkive.com/0eQ91kHG/perl-5-26-will-remove-current-directory-from-inc

**Comment by melezhik** [comment]
Обновите Sparrowdo из гита и запустите bootstrap - должно помочь. Вот этот коммит- https://github.com/melezhik/sparrowdo/commit/46e86120c005889d6f8b231b1f7bbed9c2ffb744

**Comment by Spigell** [comment]
Да, эта переменная помогла. 
А почему этот модуль вы поставляете вместе с sparrow, если не секрет?

**Comment by melezhik** [comment]
Это просто специфика данного инсталлятора. Вобщем я подумаю что можно сделать.

**Comment by melezhik** [comment]
Добавил универсальный бутстрап для всех поддерживаемых ОС , в том числе для archlinux, нужно тестировать , обратите внимание что для archlinux мне пришлось добавить ( у меня на вагрант боксе почему то не ставился Sparrow без обновления всех пакетов системы ) :

```
pacman -Syu --noconfirm
```

Так что будьте аккуратны.  Эту строчку можно обсудить, буду признателен за ваш совет на эту тему.

**Comment by melezhik** [comment]
у меня бутстрап успешно прошел для вагрант боксов на следующих системах:

- alpine
- archlinux
- centos7
- fedora
- ubuntu-trusty64

**Comment by Spigell** [comment]
> Добавил универсальный бутстрап для всех поддерживаемых ОС , в том числе для archlinux, нужно тестировать , обратите внимание что для archlinux мне пришлось добавить ( у меня на вагрант боксе почему то не ставился Sparrow без обновления всех пакетов системы ) 

А не подскажите, какой бокс используете? 

Возможно, ошибка была `does not match executable architecture` от perl-err?
Мне в этом случае помогало обновление пакета perl-Error на fedora. На archlinux не испытывал проблем. Скорее всего, потому что я часто обновляюсь. 
На archlinux rolling release, и неосмотрительное обновление всех пакетов *иногда* может что-то сломать. Поэтому не хотелось бы обновлять все пакеты ради sparrow. Скорее всего, надо обновить один пакет.

**Comment by Spigell** [comment]
Сейчас проверил на archlinux. Вы в скрипте bootstrap.sh не устанавливаете пакеты gcc make и т.д.
На только что созданной системе у меня такое:
```
[spigell@hammerhead arch_install]$ ~/.perl6/bin/sparrowdo --ssh_port=2222 --ssh_user=root --bootstrap 
running sparrow bootstrap for host: 127.0.0.1 ... 
bootstrap for archlinux
/usr/sbin/curl
installing cpanm ...
/usr/sbin/perl
:: Synchronizing package databases...
 core is up to date
 extra is up to date
 community is up to date
:: Starting full system upgrade...
 there is nothing to do
error: package 'make' was not found
The spawned command 'ssh -o ConnectionAttempts=1  -o ConnectTimeout=5 -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -tt -q -p 2222 root@127.0.0.1 "sudo bash -c 'export LC_ALL=C ; export GIT_PROTOCOL=https ; export PERL_USE_UNSAFE_INC=1 ; export PATH=/usr/bin/site_perl:/usr/local/bin:/usr/sbin/:/sbin/:/bin/$PATH ; export SPARROW_ROOT=/opt/sparrow ; export SPARROW_CONF_PATH=/opt/sparrow/sparrow-cache/sparrow.yaml ; bash /opt/sparrow/sparrowdo-cache/bootstrap.sh'" 2>/dev/null' exited unsuccessfully (exit code: 1)
  in sub MAIN at /home/spigell/.perl6/resources/8F4F4A1E61CFAC2488D33B3C7CBE57BCB97979FB line 89
  in block <unit> at /home/spigell/.perl6/resources/8F4F4A1E61CFAC2488D33B3C7CBE57BCB97979FB line 293

```
Наверно в вагрант боксах они есть, но по-умолчанию (точнее то, как [предлагается](https://wiki.archlinux.org/index.php/Installation_guide#Installation) ставить archlinux) они отсутствуют.

**Comment by melezhik** [comment]
Приветствую!  Бокс был такой - terrywang/archlinux с atlas.hashicorp.com

При установке Perl модулей, зависимостей для Sparrow вываливалась такая ошибка - `make: error while loading shared libraries: libguile-2.2.so.1: cannot open shared object file: No such file or directory` 

Решил ее обновлением системы , как советуют здесь - https://bbs.archlinux.org/viewtopic.php?id=225523

Может у меня какой-то просто старый образ архлинукса был ?

Можете попробовать воспроизветси ошибку у себя, команды для bootstrap в archlinux можно посмотреть тут -  https://github.com/melezhik/sparrowdo/blob/master/bin/sparrowdo  `sub bootstrap`

**Comment by melezhik** [comment]
> На archlinux rolling release, и неосмотрительное обновление всех пакетов иногда может что-то сломать. Поэтому не хотелось бы обновлять все пакеты ради sparrow. Скорее всего, надо обновить один пакет.

Хорошо, уберу обновление всех пакетов тогда

**Comment by melezhik** [comment]
> error: package 'make' was not found

думаю это должно помочь

**Comment by Spigell** [comment]
```
[spigell@hammerhead ~]$ ~/.perl6/bin/sparrowdo --ssh_port=2222 --ssh_user=root --bootstrap
running sparrow bootstrap for host: 127.0.0.1 ... 
bootstrap for archlinux
/usr/sbin/curl
installing cpanm ...
/usr/sbin/perl
error: package 'base-devel' was not found
```
Почему бы необходимые пакеты не ставить, как делаете для centos/deb/ubuntu, чтобы наверняка?
Попробую образ.

**Comment by melezhik** [comment]
видимо я ошибся, это не пакет, а группа пакетов - https://www.archlinux.org/groups/i686/base-devel/ , сейчас попробую по-другому

**Comment by Spigell** [comment]
Vagrant был сделан из образа 4-х летней давности. За это время многое утекло, библиотеки поменяли свое место. Поэтому автор предлагает сразу обновлять все пакеты.
А мы ставим новый cpanm и получаем ошибку. 
Но давайте будем расчитывать, что  пользователь каждый месяц сам делает обновления. Я думаю, все будет ставиться нормально.

**Comment by melezhik** [comment]
отревертил изменения - 984dbe550e226caad580643601f46d792e62776b , попробуйте снова, у меня для terrywang/archlinux пакеты gcc, make резолвятся

**Comment by melezhik** [comment]
> Vagrant был сделан из образа 4-х летней давности. За это время многое утекло, библиотеки поменяли свое место. Поэтому автор предлагает сразу обновлять все пакеты.
А мы ставим новый cpanm и получаем ошибку.
Но давайте будем расчитывать, что пользователь каждый месяц сам делает обновления. Я думаю, все будет ставиться нормально.

Я примерно так и думал. Просто хотел что бы вы сами посмотрели ( имя бо'льший опыт в archlinux ), полностью с вами согласен.

**Comment by Spigell** [comment]
Проблема в том, что если их нет, то проверять нечего. Давайте их ставить 
`pacman -S gcc `
`pacman -S make`
В самом начале, после установки на диск, в системе нет этих пакетов по-умолчанию.

**Comment by melezhik** [comment]
так ? 9d47376

**Comment by melezhik** [comment]
так вы хотели? - 9a68630

**Comment by melezhik** [comment]
а можете еще раз посмотреть https://github.com/melezhik/sparrowdo/blob/master/bin/sparrowdo#L404-L427 - бутстрап для archlinux - и если что найдете, что можно изменить  - просто засылайте pull request ... ?

**Comment by Spigell** [comment]
Да, конечно.

**Comment by melezhik** [comment]
в итоге сейчас там код такой:

```
  if ! which curl 2>/dev/null; then
     pacman -Q -q curl
  fi

  if ! which cpanm 2>/dev/null; then
    echo "installing cpanm ..."
    curl -s -kL http://cpanmin.us/ -o /bin/cpanm
    chmod a+x /bin/cpanm
  fi

  if ! which perl 2>/dev/null; then
    pacman -Sy
    pacman -Q -q perl
  fi

  if ! which sparrow 2>/dev/null; then
    pacman -S gcc make
    cpanm -q Outthentic Sparrow || cpanm -q Outthentic Sparrow
  fi

```


Но что-то мне подсказывает, что я что-то не так сделал по незнанию pacman менеджера ...

**Comment by Spigell** [comment]
https://github.com/Spigell/sparrowdo/commit/96a0f6b00c4a5553ffa61d3d5f77d486342e0d9e

А попробуйте так. Считаю, что не нужно подавлять вывод pacman. 
Попробуйте на боксе. Сейчас не могу отловить проблему. 
Не понимаю, почему. Считал, что из-за старой версии guile (была 2.0.14-1), но и с ней ставится сейчас.
В моем варианте есть такой пробел, что если каким-то образом sparrow был поставлен, не ставя cpanm, то upgrade дальше не удастся, но зато сам bootstrap быстрее стал немного.

**Comment by Spigell** [comment]
https://github.com/Spigell/sparrowdo/commit/c2ae15055263db4594662fcef520c9e8562016a6
Хотя так будет правильней наверно.
А вообще можно чуть уменьшить число повторяющихся строчек, особенно для установки cpanm и установки Sparrow. Может это в функцию стоит выделить?

**Comment by melezhik** [comment]
Спасибо за пул реквест , посмотрю чуть позже. 

Хочу немного прояснить:

> В моем варианте есть такой пробел, что если каким-то образом sparrow был поставлен, не ставя cpanm, то upgrade дальше не удастся

А каким образом вы ставите Sparrow, не ставя cpanm ?  Или я неправильно понял вашу фразу ?

**Comment by melezhik** [comment]
> А вообще можно чуть уменьшить число повторяющихся строчек, особенно для установки cpanm и установки Sparrow. Может это в функцию стоит выделить?

Можно , я бы только пришёл сначала к окончательному варианту с archlinux , а потом зарефачил ...

**Comment by Spigell** [comment]
> А каким образом вы ставите Sparrow, не ставя cpanm ? Или я неправильно понял вашу фразу ?
Ну через cpan, к примеру. Я так не делаю, но это, возможно.
Во втором коммите 100% будет ставится cpanm, если его нет.

**Comment by melezhik** [comment]
Я вас понял, а вы не выяснили как установка sparrow не через cpanm мешает апгрейду archlinux? Вобще говоря ведь sparrow это CPAN модуль и пика не должен пересекаться с системными пакетами и мешать апгрейду ...

**Comment by melezhik** [comment]
Запустил бутстрап на вашей версии boostrap для archlinux, получил ту самую ошибку, о которой писал ранее - `/usr/sbin/make: error while loading shared libraries: libguile-2.2.so.1: cannot open shared object file: No such file or directory`

Подробный лог здесь - https://gist.github.com/melezhik/c2ccfcfa3543f26125e15407133e97bb

**Comment by melezhik** [comment]
Проблема видимо в том, что утсановленная версия gulie на вагрантбоксе - старая 
```
root@archlinux:/home/vagrant# pacman -Qs guile
local/guile 2.0.14-1
    Portable, embeddable Scheme implementation written in C
```

**Comment by melezhik** [comment]
вот этот коммит решило проблему - defb3de

```
melezhik@melezhik-pc:~/projects/sparrowdo$ sparrowdo --ssh_private_key=/home/melezhik/projects/vboxes/archlinux/.vagrant/machines/default/virtualbox/private_key --ssh_user=vagrant --bootstrap --ssh_port=2200
running sparrow bootstrap for host: 127.0.0.1 ... 
bootstrap for archlinux
/usr/sbin/curl
/usr/sbin/cpanm
:: Synchronizing package databases...
 core is up to date
 extra is up to date
 community is up to date
 archlinuxfr is up to date
resolving dependencies...
looking for conflicting packages...

Packages (1) guile-2.2.2-1

Total Download Size:    5.61 MiB
Total Installed Size:  43.83 MiB
Net Upgrade Size:      32.02 MiB

:: Proceed with installation? [Y/n] 
:: Retrieving packages...
 guile-2.2.2-1-x86_64                              5.6 MiB  3.15M/s 00:02 [#########################################] 100%
(1/1) checking keys in keyring                                            [#########################################] 100%
(1/1) checking package integrity                                          [#########################################] 100%
(1/1) loading package files                                               [#########################################] 100%
(1/1) checking for file conflicts                                         [#########################################] 100%
(1/1) checking available disk space                                       [#########################################] 100%
:: Processing package changes...
(1/1) upgrading guile                                                     [#########################################] 100%
:: Running post-transaction hooks...
(1/2) Arming ConditionNeedsUpdate...
(2/2) Updating the info directory file...
/usr/sbin/perl
/usr/sbin/gcc
/usr/sbin/make
Successfully installed JSON-2.94
Successfully installed Outthentic-DSL-0.2.8
Successfully installed ExtUtils-Config-0.008
Successfully installed ExtUtils-InstallPaths-0.011
Successfully installed ExtUtils-Helpers-0.026
Successfully installed Module-Build-Tiny-0.039
Successfully installed File-ShareDir-Install-0.11
Successfully installed Class-Inspector-1.31
Successfully installed File-ShareDir-1.104
Successfully installed Capture-Tiny-0.46
Successfully installed Config-General-2.63
Successfully installed Clone-0.39
Successfully installed Hash-Merge-0.200
Successfully installed Spiffy-0.46
Successfully installed Text-Diff-1.44
Successfully installed Test-Base-0.88
Successfully installed Test-YAML-1.06
Successfully installed YAML-1.23
Successfully installed Outthentic-0.2.37
Successfully installed Try-Tiny-0.28
Successfully installed Path-Tiny-0.104
Successfully installed Module-CPANfile-1.1002
Successfully installed Class-Tiny-1.006
Successfully installed Module-Reader-0.003003
Successfully installed App-cpanminus-1.7043
Successfully installed Carton-v1.0.28
Successfully installed Config-Tiny-2.23
Successfully installed swat-0.1.96
Successfully installed Sparrow-0.2.39
29 distributions installed
Outthentic is up to date. (0.2.37)
Sparrow is up to date. (0.2.39)
running sparrow tasks on 127.0.0.1 ... 
target OS is - archlinux

```

**Comment by Spigell** [comment]
Здравствуйте. Так и должна быть на этом боксе. Но опять же, это частный случай, вязанный со старым пакетом. А если в другой раз другой пакет будет старый, то эту ситуацию тоже надо будет фиксить? Давайте для этой ОС не будем сильно углублятся. Просто Арч это не centos или ubuntu LTS, мейнтейнеры бывают все ломают без обратной совместимости ради новых версий или по каким-то другим причинам.
В строчке https://github.com/Spigell/sparrowdo/commit/96a0f6b00c4a5553ffa61d3d5f77d486342e0d9e#diff-90aa1e74a36cbebd69fa1639caee5538R435 в случае, если не получится установить аутлентик и спарроу, то появится сообщение, что что-то пошло не так, и, скорее всего, надо обновить пакеты. Я думаю, этого достаточно.

**Comment by melezhik** [comment]
Хорошо. Оставим все-таки  workaround для guile? По крайней мере он для меня подходит ...

**Comment by Spigell** [comment]
Да, давайте оставим.

**Comment by melezhik** [comment]
Пропиарил немного ваш плагин - https://redd.it/6lkg10  )))

**Comment by melezhik** [comment]
А вот это фраза что по русски означает - "Try 'pacman -Syu' if sparrow doesn't install later."

- "Попытайтесь запустить `pacman -Syu` если перед этим у вас не получилось установить sparrow " ?

**Comment by Spigell** [comment]
Хм, насколько я понял, вы дальше обновляете sparrow, но уже с --notest
https://github.com/melezhik/sparrowdo/blob/master/bin/sparrowdo#L496
Иногда это решает проблему и sparrow ставится.

Ну фраза в моей голове звучала так:
Попытайтесь запустить pacman -Syu если sparrow не установится позже.
Надо наверно так:
Try 'pacman -Syu' if sparrow won't install later.

**Comment by Spigell** [comment]
> Пропиарил немного ваш плагин - https://redd.it/6lkg10 )))
Спасибо.

**Comment by melezhik** [comment]
> Ну фраза в моей голове звучала так:
Попытайтесь запустить pacman -Syu если sparrow не установится позже.
Надо наверно так:
Try 'pacman -Syu' if sparrow won't install later.

Ок, понял вас. Немного переписал фразу - ac20ca7

**Comment by melezhik** [comment]
> Хм, насколько я понял, вы дальше обновляете sparrow, но уже с --notest
https://github.com/melezhik/sparrowdo/blob/master/bin/sparrowdo#L496
Иногда это решает проблему и sparrow ставится.

Да, эта такой трюк - иногда попомогает, когда недобросоветсные майнтейнеры не прописывают зависимости в CPAN модулях и в первый прогон что-то не ставится.  Тогда делается пара прогонов еще. `notest` просто опускает запуск юнит тестов - чисто для скорости выполнения, это конечно не вседа хорошо ... но ... предлагаю пока так оставить , что думаете?

**Comment by Spigell** [comment]
Да, давайте оставим.
