### ISSUE TITLE
Add sparrowdo option for PATH

### ISSUE THREAD

**Issue by Spigell** [melezhik/sparrowdo#7]
Здравствуйте. Не очень важное добавление, но было бы неплохо. Sparrowdo ищет sparrow в тех местах, которые указаны в переменной PATH.
```
[spigell@hammerhead sparrowdo]$ ~/.perl6/bin/sparrowdo --host=127.0.0.1 --ssh_port=2222 --sparrowfile=./code/main.pl6 --verbose
running sparrow tasks on 127.0.0.1 ... 
ssh -o ConnectionAttempts=1  -o ConnectTimeout=5 -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -tt -p 2222 127.0.0.1 "sudo bash -c 'export LC_ALL=en_US.UTF-8 ; export GIT_PROTOCOL=https ; export PATH=/sbin/:/usr/local/bin:/usr/sbin/:$PATH 
``` 
Но на некоторых ОС sparrow лежит в другом каталоге. Например, archlinux
```
[spigell@hammerhead sparrowdo]$ whereis sparrow
sparrow: /usr/bin/site_perl/sparrow
```
Пока это единственный пример, но тем не менее.

Также, на 6 centos rm и mkdir лежат в /bin и sparrowdo нормально не отрабатывает.

Возможно, через ключ --sparrow_path (или просто --env_path) было бы более правильно добавлять новые каталоги, чем через стандартную $PATH на sparrowdo-хосте.

**Comment by melezhik** [comment]
Здравствуйте! Мне почему-то кажется, что установка переменой окружения path не должна быть доступна через параметры командной строки, так как это скорее свойство конкретного целевого сервера, на котором запускается sparrow клиент. Вас устроит вариант простого добавления указанных вами путей в path, через жесткое задание в коде самого Sparrowdo ( как это сделано сейчас ) , тогда мы закроем большинство случаев ... ? То есть будет так:

       PATH=/sbin/:/usr/local/bin:/usr/sbin/:/bin/:/usr/bin/site_perl:$PATH

**Comment by Spigell** [comment]
Хорошо, давайте так.

**Comment by melezhik** [comment]
добавил новые пути в PATH, пробуйте
