### ISSUE TITLE
add hostname fact in sparrowdo

### ISSUE THREAD

**Issue by Spigell** [melezhik/sparrowdo#9]
Здравствуйте. У вас не было такой ситуации, что для ветвления в sparrowfile требовался hostname таргета (содержимое /etc/hostname)? 
Было бы неплохо добавить такой хелпер.

**Comment by melezhik** [comment]
Приветствую! 

`input_params('Host')` вам подойдет? ( https://github.com/melezhik/sparrowdo#helper-functions )

**Comment by Spigell** [comment]
Здравствуйте. Это не совсем то, что я подразумевал. `input_params` - это то, что вводит пользователь при запуске. 
Я имел ввиду реальный хостнейм на таргете, т.е. тоже самое, что сейчас есть для определения типа ОС.
Вот, к примеру такой сценарий
```
 template '/etc/chef/knife.rb', %(
   source => ( slurp 'templates/knife.rb' ),
   variables => %(
     server   => "$server",
     hostname => "$hostname",
     org      => "$org"
   )
 );
```
Чтобы получить переменную `hostname` я делаю так
```
  my $target = input_params('Host');
  my $ssh = QX("ssh $target 'cat /etc/hostname'");
  my $hostname = $ssh.chomp;
```
А хотелось бы иметь отдельный хелпер для этого. Как считаете?

**Comment by melezhik** [comment]
Да, я вас понял. Нужно подумать ...

**Comment by melezhik** [comment]
Попробуйте, обновитесь с этого коммита, смотрите в документации или в https://github.com/melezhik/sparrowdo/blob/master/examples/hostname/sparrowfile

**Comment by melezhik** [comment]
Приветствую! 
Получилось проверить?

**Comment by Spigell** [comment]
Здравствуйте. Да, работает. 
Забыл отписаться, извиняюсь.

**Comment by melezhik** [comment]
Все ок.
Тогда закрываю.
